lsi: false
safe: true
source: "." # or the path to your Jekyll source directory if it's not the root
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-minimal
avatar: /assets/images/4990.jpg
social_links:
  github: https://github.com/tumigisla
  linkedin: https://www.linkedin.com/in/tumisnaer
  farcaster: https://warpcast.com/tgislason

